---
apiVersion: v1
kind: Service
metadata:
    namespace: vote
    name: result-service
spec:
    type: NodePort
    ports:
      - port: 5001
        protocol: TCP
        targetPort: 80
        nodePort: 31001
    selector:
      app: result

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
  namespace: vote
  labels:
    app: result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - name: result
        image: kodekloud/examplevotingapp_result:before
        ports:
        - containerPort: 80
          
          

             
             